### PR TITLE
Nourishment Talisman Default Research Update 

### PR DESCRIPTION
**Pull request by Shibva**
Updated default infusion recipe to make new internal capacity change made in #26 more fitting
Note: NO, this is not modifying any GTNH recipes **UNLESS the pack is using the original recipe!** Changes are minor and should not be as much of a problem to acquire

summary:
- botch the first commit (last time I try to do it in the hub and not in the IDE... I hope) [IGNORE]
- corrected changes in the second commit (and applied spotless)

Changes:
- Infusion Ritual now requires 2 more items: a Chest and a Golden Carrot (G-Carrot was optional, more or less added to make the thing symmetrical; also conveniently fits in as a saturating item) 
- Infusion Ritual now also requires 32 Vaculos to "make the infused chest fit in the damn thing"

Test: The client was run successfully and changes were applied as so without issue
image

Technical Notes: @Dream-Master Please have someone look into this, I've noticed as the thing was building in the client before and after these changes that the VM tossed a ``java.lang.IllegalArgumentException``, making a note in case this could become a problem in the distant future for whatever reason

### CODE REVIEW

**Comment by Shibva** [comment]
edit: description format corrections

**Comment by Dream-Master** [comment]
All tc recipes normals overridden by scripts. Did you change the recipe that it match with the script ?

**Review by Dream-Master — CHANGES_REQUESTED** [review]
If the recipe not match with gt one why you update it in code? IF the recipe match i can pull.

**Comment by Shibva** [comment]
it was more in mind for normal recipies so some of these things can work out of pack 

However, I can change it to the pack and will do this

or

I can modify it to run the pack recipe if the GTNH core mod is present to allow it to able to run in and out of the pack without the need of dependencies. 

Id recommend the latter so it can allow for people to also use the fixes outside of the pack while any of the recipe changes that take place will occur and it would allow for compatibility

Regardless ill do option 1 unless you agree wtih the second idea; the next comit should update the recipe to the one in the pack

**Comment by Dream-Master** [comment]
and run spotless please

**Review by Shibva — COMMENTED** [review]
should be fine, the script will change the recipe anyway

**Comment by Alastors** [comment]
Screen Shot 2022-12-28 at 9 21 05 PM

I decline merging this until this is resolved

**Comment by miozune** [comment]
Update AppleCore dependency in `dependencies.gradle`:
```
compile('com.github.GTNewHorizons:AppleCore:3.2.3:dev')
```

**Comment by Shibva** [comment]
Note: The lang IllegalArgumentException is still present, I am in no way advanced/skilled enough to fix this issue, but itappears that it was present before my changes and was noted as existing in #26

**Review by Alastors — APPROVED** [review]
I don't fully understand the point myself, but whatever I suppose.

**Comment by Shibva** [comment]
@miozune change has corrected the lang.IllegalArgumentException error present here and in #26, meaning this issue started because it was using a newer feature of applecore and the thing depended on an version that dint have it, or so I theorize

THANKS MIOZUNE!

**Comment by Alastors** [comment]
> Note: The lang IllegalArgumentException is still present, I am in no way advanced/skilled enough to fix this issue, but itappears that it was present before my changes and was noted as existing in #26

I will note here, that this error is no longer present

**Review by Alastors — APPROVED** [review]

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
