### PR TITLE
Remove chunkloading stuff

### PR DESCRIPTION
**Pull request by Prometheus0000**
No guarantees it won't crash somehow, even though it didn't for me, since I can't even get it to turn on with the normal version. Since it's been nerfed to past the pure tear because of other bugs, it might be better just to disable its recipe.

### CODE REVIEW

**Review by mitchej123 — CHANGES_REQUESTED** [review]
I'd rather see this be a config option than just ripping it out.  Let's not force things on everyone that we're doing just for optimizations on the officials/bigger servers.

**Comment by Prometheus0000** [comment]
That would be hard though. Where would I put it, an if statement in addTicket?

**Comment by Prometheus0000** [comment]
Or if(heldChunk==null) -> if(heldChunk==null && config=true?)

**Comment by 0lafe** [comment]
I'd assume most server owners are intending for Thaum to have chunk loaders? I know on some ive played on, there have always been problems with bases being loaded for no reason, and they usually don't like that

**Comment by mitchej123** [comment]
> I'd assume most server owners are intending for Thaum to have chunk loaders? I know on some ive played on, there have always been problems with bases being loaded for no reason, and they usually don't like that

Give them the option to disable it, but leave it on for SP.

**Comment by Prometheus0000** [comment]
Changed to config option

**Comment by Dream-Master** [comment]
@mitchej123 ok now ?

**Review by mitchej123 — APPROVED** [review]
Much better as a config option, thanks!

**Pull request merged**
